project:
  type: website
  output-dir: docs

format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    navigation-mode: linear
    pdf-separate-fragments: true

resources:
  - images/
